*** Variables ***
${home_page.header_lbl}                 xpath=//div[contains(., "***string***")]
${home_page.input_user}                 xpath=//input[@placeholder="***string***"]
${home_page.button}                     xpath=//input[@value="***string***"]
${home_page.accepted_users_lbl}         xpath=//div[@id="root"]/div/div[2]/div[2]/div
${home_page.popup_msg}                  xpath=//*[@id="login_button_container"]/div/form/div[3]/h3[text()="***string***"]
${home_page.close_popup_btn}            xpath=//*[@id="login_button_container"]/div/form/div[3]/h3/button
